version: "3.7"

services:
  nginx:
    image: nginx
    ports:
       - 8008:80
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - crud-project
  frontend:
    build: ./frontend
    networks:
      - crud-project

  postgres:
    image: postgres:14-alpine
    expose:
      - 5431
    environment:
      POSTGRES_DB: backenddb
      POSTGRES_USER: backend
      POSTGRES_PASSWORD: backend
    volumes:
      - ./.docker/postgresql/:/var/lib/postgresql/data:rw
    ports:
      - "5431:5432"
    networks:
      - crud-project

  backend:
    build: ./backend
    ports:
      - 8080:8080
    depends_on:
      - postgres
    environment:
      db-url: jdbc:postgresql://postgres:5432/backenddb
      db-username: backend
      db-password: backend
    restart: always
    networks:
      - crud-project

networks:
  crud-project:
