
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${db-url:jdbc:postgresql://localhost:5432/backenddb}
    username: ${db-username:postgres}
    password: ${db-password:backend}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  artemis:
    embedded:
      server-id:
server:
  address: 0.0.0.0